'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowRight,ArrowLeft,Check,BookOpen} from 'lucide-react';
import {api,type Progress} from '@/lib/client';
import {personas,type PublicProblem} from '@/lib/domain';
import {useStudentChoice,chooseStudent} from '@/lib/student-choice';
import {chapterTwoId,chapterTwoTitle,pendingGraphProblem,defaultChapterTwoProblem} from '@/lib/course';
import {Avatar} from './visuals';
export function Library({studentId,chapter='chapter-2',manual=false}:{studentId?:string;chapter?:string;manual?:boolean}){
 const choice=useStudentChoice(),student=personas.find(p=>p.id===(studentId??choice))!;
 useEffect(()=>{if(studentId)chooseStudent(studentId);},[studentId]);
 const [selected,setSelected]=useState(chapter),[problems,setProblems]=useState<PublicProblem[]>([]),[progress,setProgress]=useState<Progress|null>(null),[error,setError]=useState('');
 useEffect(()=>{Promise.all([api<PublicProblem[]>('problems'),api<Progress>('progress')]).then(([p,g])=>{setProblems(p);setProgress(g);}).catch(e=>setError(e.message));},[]);
 const chapterTwo=selected===chapterTwoId;
 const list=problems.filter(p=>chapterTwo?p.chapterId===chapterTwoId:p.kind==='original-demo').sort((a,b)=>(a.problemNumber??0)-(b.problemNumber??0));
 return <div className="page library"><Link className="breadcrumb" href={`/classroom?student=${student.id}`}><ArrowLeft size={14}/>Back to classroom</Link><div className="eyebrow">YOUR COURSE SHELF</div><div className="page-title"><h1>{manual?'Manual library':'Problem library'}</h1><p>{manual?'Authored steps and hands-on practice.':'Choose something to work through together.'}</p></div><div className="library-student"><Avatar id={student.id} size={40}/><span>Learning with {student.name.split(' ')[0]}</span><Link className="text-button" href="/students">Change student <ArrowRight size={15}/></Link></div><nav className="library-sections" aria-label="Library sections"><Link aria-current={!manual?'page':undefined} href={`/library?student=${student.id}&chapter=${selected}`}>Problems</Link><Link aria-current={manual?'page':undefined} href={`/library?section=manual&student=${student.id}&chapter=${selected}`}>Manual</Link></nav><div className="library-chapters segmented" role="group" aria-label="Choose a chapter"><button aria-pressed={chapterTwo} className={chapterTwo?'selected':''} onClick={()=>setSelected(chapterTwoId)}>Chapter 2</button><button aria-pressed={!chapterTwo} className={!chapterTwo?'selected':''} onClick={()=>setSelected('demo')}>Demos</button></div><section className="library-chapter-heading"><BookOpen size={23}/><div><span className="label">{chapterTwo?'CHAPTER 2':'DEMO COLLECTION'}</span><h2>{chapterTwo?chapterTwoTitle:'Circular Motion & Newton’s Laws'}</h2><p>{chapterTwo?'9 ready to teach · 1 waiting for its graph':'6 original examples to explore the teaching flow'}</p></div></section>{error&&<p className="error" role="alert">{error}</p>}{!problems.length&&!error&&<p role="status">Opening the shelf…</p>}<div className="problem-list">{list.map((p,i)=>{const done=progress?.sessions.some(s=>s.title===p.title&&s.state==='completed');return <Link className="problem-row" key={p.id} href={manual?`/library/manual/${p.id}?student=${student.id}`:`/problems/${p.id}?student=${student.id}`}><span className="problem-index">{p.problemNumber??String(i+1).padStart(2,'0')}</span><div><h3>{p.title}</h3><p>{p.subtitle}</p>{p.id===defaultChapterTwoProblem&&<span className="default-problem">Classroom default</span>}</div><span className="problem-source">{manual?'Step-by-step':done?<><Check size={13}/>Taught</>:chapterTwo?'Chapter 2':'Original demo'}</span><ArrowRight size={18}/></Link>;})}{chapterTwo&&<article className="problem-row pending-problem"><span className="problem-index">17</span><div><h3>{pendingGraphProblem.title}</h3><p>{pendingGraphProblem.description}</p><p className="pending-note">{pendingGraphProblem.reason}</p></div><span className="pill muted">Needs figure</span></article>}</div></div>;
}
