'use client';
import {useState,useEffect} from 'react';
import {signIn,signOut} from 'next-auth/react';
import {Lock,Plus,Save,Check} from 'lucide-react';
import {api} from '@/lib/client';
type Version={id:string;version:number;status:string;data:unknown};type OwnerProblem={id:string;versions:Version[]};
export function Owner(){const [owner,setOwner]=useState(false),[configured,setConfigured]=useState(false),[problems,setProblems]=useState<OwnerProblem[]>([]),[selected,setSelected]=useState(''),[source,setSource]=useState(''),[reviewNote,setReviewNote]=useState(''),[checked,setChecked]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 async function refresh(){const config=await api<{owner:boolean;authenticationConfigured:boolean}>('config');setOwner(config.owner);setConfigured(config.authenticationConfigured);setLoaded(true);if(config.owner){const p=await api<OwnerProblem[]>('owner/problems');setProblems(p);}}
 useEffect(()=>{api<{owner:boolean;authenticationConfigured:boolean}>('config').then(async config=>{setOwner(config.owner);setConfigured(config.authenticationConfigured);setLoaded(true);if(config.owner)setProblems(await api<OwnerProblem[]>('owner/problems'));}).catch(e=>{setError(e.message);setLoaded(true);});},[]);
 function select(id:string){const p=problems.find(p=>p.id===id);setSelected(id);setSource(p?JSON.stringify(p.versions[0].data,null,2):'');setChecked(false);setMessage('');}
 async function save(status:'draft'|'review'){setBusy(true);setError('');try{const data=JSON.parse(source);if(selected){await api(`owner/problems/${selected}`,{method:'POST',body:{data,status}});}else{const result=await api<OwnerProblem>('owner/problems',{method:'POST',body:{chapterId:'circular-motion',data}});setSelected(result.id);}await refresh();setMessage(`Saved a new ${status} version. Published versions and existing sessions stay pinned.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function publish(){const version=problems.find(p=>p.id===selected)?.versions[0];if(!version)return;setBusy(true);setError('');try{await api(`owner/problems/${selected}/publish`,{method:'POST',body:{versionId:version.id,reviewNote,confirmReviewed:checked}});await refresh();setMessage('Published an immutable problem version. New sessions can use it.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!loaded)return <div className="page" role="status">Checking owner access…</div>;
 if(!owner)return <div className="page centered"><Lock size={38}/><div className="eyebrow">OWNER-ONLY CONTENT STUDIO</div><h1>A place for<br/><em>reviewed physics.</em></h1><p>Only the configured owner can create, review, and publish content.<br/>Teacher mode is a learning role and grants no editing permissions.</p>{configured?<button className="button" onClick={()=>void signIn('github',{callbackUrl:'/owner'})}>Sign in with owner GitHub account</button>:<p className="paper auth-note">Owner authentication is not configured. Set the GitHub OAuth credentials and immutable owner account ID on the server to enable the content studio.</p>}{error&&<p className="error" role="alert">{error}</p>}</div>;
 const current=problems.find(p=>p.id===selected)?.versions[0];return <div className="page owner-page"><div className="eyebrow">OWNER-ONLY CONTENT STUDIO</div><h1>The next chapter<br/><em>starts with good questions.</em></h1><div className="action-row"><select aria-label="Choose content to edit" value={selected} onChange={e=>select(e.target.value)}><option value="">Create a new problem</option>{problems.map(p=><option key={p.id} value={p.id}>{p.id} · v{p.versions[0].version} · {p.versions[0].status}</option>)}</select><button className="text-button" disabled={!selected} onClick={()=>{setSelected('');setMessage('Copied into a new problem. Replace the content and use new versioned template IDs before saving.');}}>Copy as a new problem</button><button className="text-button" onClick={()=>void signOut({callbackUrl:'/'})}>Sign out</button></div><p>The MVP editor uses validated JSON. Copy an original problem as a starting point. Confirm textbook permissions, independently review the physics, and save a review version before publishing. Each save creates a new version.</p><label htmlFor="content-json">Problem content, reference, rubric, and approved templates</label><textarea className="code-editor" id="content-json" rows={24} value={source} onChange={e=>setSource(e.target.value)} placeholder="Select a demo problem to inspect its complete schema, or paste a complete ProblemData JSON object."/><div className="action-row"><button className="button secondary" disabled={busy||!source} onClick={()=>void save('draft')}><Plus size={15}/>Save draft</button><button className="button" disabled={busy||!selected} onClick={()=>void save('review')}><Save size={15}/>Save review version</button></div><section className="paper settings-section"><Check size={24}/><div><h2>Publish reviewed version {current?.version??'—'}</h2><label htmlFor="review-note">Independent review notes</label><textarea id="review-note" value={reviewNote} onChange={e=>setReviewNote(e.target.value)} rows={3} placeholder="Document algebra, units, force directions, numerical target, tolerances, and permission review."/><label className="toggle-label"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>I reviewed the solution and approved error templates and have permission to use this content.</label><button className="button" disabled={busy||!checked||reviewNote.length<20||current?.status!=='review'} onClick={()=>void publish()}>Publish immutable version</button></div></section>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="feedback accepted">{message}</p>}</div>;
}
