'use client';
import {useState} from 'react';
import Image from 'next/image';
import {Download,ShieldCheck} from 'lucide-react';
import {api} from '@/lib/client';
import {AudioControls} from './shell';
import {ConfirmDialog} from './workspace';
export function Settings(){const [deleting,setDeleting]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function exportHistory(){setBusy(true);setError('');try{const data=await api('history/export');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='professor-shalvas-classroom-history.json';a.click();URL.revokeObjectURL(url);setMessage('Your history export is ready. Active sessions include only visible work.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function removeHistory(){setDeleting(false);setBusy(true);try{const data=await api<{deleted:number}>('history',{method:'DELETE',body:{confirm:'DELETE MY HISTORY'}});setMessage(`Deleted ${data.deleted} sessions from your active history.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="page settings-page"><picture className="settings-skate"><source media="(prefers-reduced-motion: reduce)" srcSet="/images/settings-skate-still.png"/><Image src="/images/settings-skate.gif" width={750} height={750} alt="" unoptimized loading="eager"/></picture><div className="settings-content"><div className="eyebrow">PREFERENCES</div><h1>Settings</h1><section className="paper settings-section"><ShieldCheck size={25}/><div><h2>Your history</h2><div className="action-row"><button className="button secondary" disabled={busy} onClick={()=>void exportHistory()}><Download size={16}/>Export my history</button><button className="text-button danger" disabled={busy} onClick={()=>setDeleting(true)}>Delete my history</button></div></div></section><section className="paper settings-section"><span className="original-mark" aria-hidden="true">✦</span><div><h2>AI & sound</h2><p>Mock demonstrations make no OpenAI calls. Live sessions send problem content, corrections, and conversation messages to OpenAI through the server. The application uses <code>store:false</code>; this is not a guarantee of zero provider retention. Keep personal information out of your explanations.</p><div className="settings-audio"><AudioControls/></div><p>Listen to lofi.cafe, or choose Offline for Moonlit Desk, our original lo-fi track.</p></div></section>{message&&<p role="status" className="feedback accepted">{message}</p>}{error&&<p role="alert" className="error">{error}</p>}{deleting&&<ConfirmDialog title="Delete your teaching history?" confirmLabel="Delete my history" onClose={()=>setDeleting(false)} onConfirm={()=>void removeHistory()}><p>This removes all sessions, corrections, scores, and hint records owned by your current identity. The action cannot be undone in the application. Download an export first if you want a copy.</p></ConfirmDialog>}</div></div>;
}
