'use client';
import {useState,useEffect} from 'react';
import {Download,ShieldCheck,Sun} from 'lucide-react';
import {api} from '@/lib/client';
import {AudioControls} from './shell';
import {AiSettings} from './ai-settings';
import {ConfirmDialog} from './workspace';
export function Settings(){const [contrast,setContrast]=useState(false),[deleting,setDeleting]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{queueMicrotask(()=>setContrast(localStorage.getItem('chalklight-contrast')==='high'));},[]);
 async function exportHistory(){setBusy(true);setError('');try{const data=await api('history/export');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='professor-shalvas-classroom-history.json';a.click();URL.revokeObjectURL(url);setMessage('Your history export is ready. Active sessions include only visible work.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function removeHistory(){setDeleting(false);setBusy(true);try{const data=await api<{deleted:number}>('history',{method:'DELETE',body:{confirm:'DELETE MY HISTORY'}});setMessage(`Deleted ${data.deleted} sessions from your active history.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="page settings-page"><div className="eyebrow">PREFERENCES</div><h1>Settings</h1><AiSettings/><section className="paper settings-section"><Sun size={25}/><div><h2>Focus & accessibility</h2><p>Higher contrast, crisp borders, and clearer reading. Keyboard focus is always visible. Your device’s reduced-motion preference is respected.</p><label className="toggle-label"><input type="checkbox" checked={contrast} onChange={e=>{setContrast(e.target.checked);localStorage.setItem('chalklight-contrast',e.target.checked?'high':'normal');document.documentElement.dataset.contrast=e.target.checked?'high':'normal';}}/>High-contrast focus mode</label></div></section><section className="paper settings-section"><ShieldCheck size={25}/><div><h2>Your history</h2><p>A signed, HttpOnly guest cookie links this browser to your saved sessions. We keep corrections, session steps, hint use, and formative scores. Guest sessions are eligible for cleanup after 30 inactive days, configurable by the owner.</p><div className="action-row"><button className="button secondary" disabled={busy} onClick={()=>void exportHistory()}><Download size={16}/>Export my history</button><button className="text-button danger" disabled={busy} onClick={()=>setDeleting(true)}>Delete my history</button></div><p className="tiny">Deletion removes active application records. Backups can retain deleted data until their configured retention expires; the local demo does not create backups.</p></div></section><section className="paper settings-section"><div className="original-mark">✦</div><div><h2>AI & sound</h2><p>Mock demonstrations make no OpenAI calls. Live sessions send problem content, corrections, and conversation messages to OpenAI through the server. The application uses <code>store:false</code>; this is not a guarantee of zero provider retention. Keep personal information out of your explanations.</p><div className="settings-audio"><AudioControls/></div><p>Moonlit Desk is an original 74 BPM lo-fi loop: soft keys, warm bass, and a gentle beat. Play it here or in the sidebar. Music stays in sync as you move between pages; volume and mute preferences are remembered.</p><p className="tiny">Student profile pictures and course sources are documented in Course notes. The original demos remain available in Library.</p></div></section>{message&&<p role="status" className="feedback accepted">{message}</p>}{error&&<p role="alert" className="error">{error}</p>}{deleting&&<ConfirmDialog title="Delete your teaching history?" confirmLabel="Delete my history" onClose={()=>setDeleting(false)} onConfirm={()=>void removeHistory()}><p>This removes all sessions, corrections, scores, and hint records owned by your current identity. The action cannot be undone in the application. Download an export first if you want a copy.</p></ConfirmDialog>}</div>;
}
