'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,Check,ShieldCheck} from 'lucide-react';
import {api,key} from '@/lib/client';
import {personas,type PublicProblem,type PublicSession} from '@/lib/domain';
import {useStudentChoice,chooseStudent} from '@/lib/student-choice';
import {Avatar,Diagram} from './visuals';
export function Setup({id,studentId}:{id:string;studentId?:string}){
 const choice=useStudentChoice(),persona=studentId??choice;
 useEffect(()=>{if(studentId)chooseStudent(studentId);},[studentId]);
 const [problem,setProblem]=useState<PublicProblem|null>(null),[difficulty,setDifficulty]=useState('guided'),[provider,setProvider]=useState('mock'),[live,setLive]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);const router=useRouter();
 useEffect(()=>{Promise.all([api<PublicProblem>(`problems/${id}`),api<{liveEnabled:boolean}>('config')]).then(([p,c])=>{setProblem(p);setLive(c.liveEnabled);}).catch(e=>setError(e.message));},[id]);
 async function start(){setBusy(true);setError('');try{const s=await api<PublicSession>('sessions',{method:'POST',body:{problemId:id,personaId:persona,difficulty,provider,idempotencyKey:key()}});router.push(`/sessions/${s.id}`);}catch(e){setError((e as Error).message);setBusy(false);}}
 if(!problem)return <div className="page" role={error?'alert':'status'}>{error||'Opening the problem…'}</div>;
 return <div className="page setup"><Link className="breadcrumb" href={`/library?student=${persona}`}><ArrowLeft size={14}/>Problem library</Link><div className="eyebrow">{problem.chapterId==='chapter-2'?`CHAPTER 2 · PROBLEM ${problem.problemNumber}`:'CIRCULAR MOTION DEMOS'}</div><h1>{problem.title}</h1><p className="subtitle">{problem.subtitle}</p>
 <div className="problem-preview"><article className="problem-detail"><h2>The question</h2><p className="statement">{problem.statement}</p><Diagram kind={problem.diagram} caption={problem.diagramCaption} large/><div className="givens"><h3>What we know</h3><dl>{problem.givens.map(g=><div key={g.symbol}><dt>{g.symbol}</dt><dd>{g.value} <span>{g.unit}</span></dd></div>)}</dl></div><h3>Learning objectives</h3><ul className="checklist">{problem.objectives.map(o=><li key={o}><Check size={15}/>{o}</li>)}</ul><details><summary>Assumptions & content notes</summary><ul>{problem.assumptions.map(a=><li key={a}>{a}</li>)}</ul><p>{problem.source}. {problem.permission}</p><p>Required diagram: {problem.diagramRequired?'yes':'no'}. Rubric: {problem.rubric.join('; ')}.</p></details></article>
 <section className="setup-options"><div className="chosen-student"><Avatar id={persona} size={48}/><div><strong>{personas.find(p=>p.id===persona)?.name}</strong><p>Your student for this problem.</p></div></div><h2>Meet at the board.</h2><p>Watch your student work through each step. Ask questions, check their reasoning, and explain corrections together.</p><details className="session-options"><summary>Session settings</summary><h3>Difficulty</h3><div className="segmented" role="group" aria-label="Difficulty">{['guided','standard','challenge'].map(d=><button key={d} aria-pressed={difficulty===d} className={difficulty===d?'selected':''} onClick={()=>setDifficulty(d)}>{d}</button>)}</div><p className="tiny difficulty-help">{difficulty==='guided'?'One root issue, a checklist, and equation support.':difficulty==='standard'?'Two independent root issues, with hints when you need them.':'Up to three eligible root issues, with less scaffolding.'}</p><label className="field-label" htmlFor="provider">AI provider</label><select id="provider" value={provider} onChange={e=>setProvider(e.target.value)}><option value="mock">Reviewed mock demonstration · no API calls</option><option value="live" disabled={!live}>Live OpenAI {live?'· sends feedback to OpenAI':'· not configured'}</option></select><p className="tiny">{provider==='mock'?'Controlled mistakes and a limited deterministic checker. No feedback is sent to OpenAI.':'Your corrections are sent to OpenAI; store:false is not a zero-retention guarantee. No automatic provider switching.'}</p></details><p className="setup-mode tiny">{difficulty} · {provider==='mock'?'Mock responses':'Live OpenAI'}</p><button className="button full" onClick={start} disabled={busy}>{busy?'Preparing your student…':'Open classroom board'}<ArrowRight size={18}/></button><p className="setup-saved tiny"><ShieldCheck size={14}/>Progress saves automatically</p>{error&&<p className="error" role="alert">{error}</p>}</section></div></div>;
}
